keys:
  - &user_frost age18nxy7sktfka6u0qtyeej7dqz95zqqyfyc7yg34r56h933zu9x49q6j3v3k
  - &user_tester age1ak7kqu9gn7c37xf0mw85m7sdylnsntcwzkfvs24p22zydpwnrq0qv3czy9

  - &host_andromeda age1a2jks6zj56nfmgx0055kfdqnwuaawuzl69lkm5elv8s0cetacgxs5hfsx9
  - &host_perseus age1xeqspuvenjahkmf99y560r5yfcvtymzv5pg7vyje7lgwyw9qeuesssmgkm
creation_rules:
  - path_regex: secrets/users/frost.yaml
    key_groups:
      - age: [ *user_frost ]
  - path_regex: secrets/users/tester.yaml
    key_groups:
      - age: [ *user_tester ]

  - path_regex: secrets/hosts/andromeda.yaml
    key_groups:
      - age: [ *host_andromeda ]
  - path_regex: secrets/hosts/perseus.yaml
    key_groups:
      - age: [ *host_perseus ]
